FROM registry.access.redhat.com/ubi9/ubi

RUN mkdir -p /tmp/rpms /root/rpmbuild/SRPMS
COPY haproxy*.rpm /tmp/rpms/

RUN INSTALL_PKGS="rsyslog procps-ng util-linux socat" && \
    yum install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    if ls /tmp/rpms/*src.rpm 2>/dev/null; then rm /tmp/rpms/*src.rpm; fi && \
    if ls /tmp/rpms/*.rpm 2>/dev/null; then dnf install -y /tmp/rpms/*.rpm; fi && \
    yum clean all && \
    mkdir -p /var/lib/haproxy/router/{certs,cacerts,whitelists} && \
    mkdir -p /var/lib/haproxy/{conf/.tmp,run,bin,log,mtls} && \
    touch /var/lib/haproxy/conf/{{os_http_be,os_edge_reencrypt_be,os_tcp_be,os_sni_passthrough,os_route_http_redirect,cert_config,os_wildcard_domain}.map,haproxy.config} && \
    setcap 'cap_net_bind_service=ep' /usr/sbin/haproxy && \
    chown -R :0 /var/lib/haproxy && \
    chmod -R g+w /var/lib/haproxy
COPY images/router/haproxy/ /var/lib/haproxy/
COPY openshift-router /usr/bin/openshift-router
USER 1001
EXPOSE 80 443 7000
WORKDIR /var/lib/haproxy/conf
ENV XDG_CONFIG_HOME=/tmp \
    TEMPLATE_FILE=/var/lib/haproxy/conf/haproxy-config.template \
    RELOAD_SCRIPT=/var/lib/haproxy/reload-haproxy
ENTRYPOINT ["/usr/bin/openshift-router", "--v=4"]
