# Test extension builder stage (added by ote-migration)
FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS test-extension-builder
RUN mkdir -p /go/src/github.com/openshift/router
WORKDIR /go/src/github.com/openshift/router
COPY tests-extension/ tests-extension/
RUN cd tests-extension && \
    make build && \
    cd bin && \
    tar -czvf router-test-extension.tar.gz router-tests-ext && \
    rm -f router-tests-ext

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9
# Copy test extension binary (added by ote-migration)
COPY --from=test-extension-builder /go/src/github.com/openshift/router/tests-extension/bin/router-test-extension.tar.gz /usr/bin/
RUN INSTALL_PKGS="socat haproxy28" && \
    yum install -y --setopt=install_weak_deps=0 $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all && \
    setcap 'cap_net_bind_service=ep' /usr/sbin/haproxy && \
    sed -i 's/SECLEVEL=2/SECLEVEL=1/g' /etc/crypto-policies/back-ends/opensslcnf.config
LABEL io.k8s.display-name="OpenShift HAProxy 2.8" \
      io.k8s.description="This component exposes the Ingress and Route rules, running as a sidecar of the Router component." \
      io.openshift.tags="openshift,haproxy"
USER 1001
EXPOSE 80 443
