FROM registry.ci.openshift.org/ocp/5.0:base-rhel9

RUN curl -fLo /tmp/haproxy.rpm https://github.com/jcmoraisjr/openshift-router/raw/refs/heads/rpms/haproxy28-2.8.27-1.rhaos4.23.el9.x86_64.rpm && \
    rpm -ivh /tmp/haproxy.rpm && \
    rm -f /tmp/haproxy.rpm && \
    haproxy -vv

RUN INSTALL_PKGS="socat" && \
    yum install -y --setopt=install_weak_deps=0 $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all && \
    setcap 'cap_net_bind_service=ep' /usr/sbin/haproxy && \
    sed -i 's/SECLEVEL=2/SECLEVEL=1/g' /etc/crypto-policies/back-ends/opensslcnf.config
LABEL io.k8s.display-name="OpenShift HAProxy 2.8" \
      io.k8s.description="This component exposes the Ingress and Route rules, running as a sidecar of the Router component." \
      io.openshift.tags="openshift,haproxy"
USER 1001
EXPOSE 80 443
