// Code generated by go-bindata. (@generated) DO NOT EDIT.

//Package testdata generated by go-bindata.// sources:
// testdata/router/49802-route.yaml
// testdata/router/ca-bundle.pem
// testdata/router/httpbin-deploy.yaml
// testdata/router/ingress-with-class.yaml
// testdata/router/ingresscontroller-np.yaml
// testdata/router/subdomain-routes/route.yaml
// testdata/router/template-web-server-deploy.yaml
// testdata/router/test-client-pod.yaml
// testdata/router/web-server-deploy.yaml
// testdata/router/web-server-signed-deploy.yaml
// testdata/router/websocket-deploy.yaml
package testdata

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _router49802RouteYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      name: service-unsecure
    name: hello-pod
  namespace: ${NAMESPACE}
  spec:
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    to:
      kind: Service
      name: service-unsecure
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      name: service-unsecure
    name: hello-pod-http
  namespace: ${NAMESPACE}
  spec:
    path: "/test"
    to:
      kind: Service
      name: service-unsecure
parameters:
- name: NAMESPACE
`)

func router49802RouteYamlBytes() ([]byte, error) {
	return _router49802RouteYaml, nil
}

func router49802RouteYaml() (*asset, error) {
	bytes, err := router49802RouteYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/49802-route.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerCaBundlePem = []byte(`-----BEGIN CERTIFICATE-----
MIIFDTCCAvWgAwIBAgIUDtkk2PPE+b/uQ8STNJNyuacqLq8wDQYJKoZIhvcNAQEL
BQAwFTETMBEGA1UEAwwKTkUtVGVzdC1DQTAgFw0yNTAxMTcwMzA0NDJaGA8yMDc1
MDExNzAzMDQ0MlowFTETMBEGA1UEAwwKTkUtVGVzdC1DQTCCAiIwDQYJKoZIhvcN
AQEBBQADggIPADCCAgoCggIBAJMUI8/l6x4IDw0uQtJo0f9kV3ogWkgi4yU6UD4c
Wln8TMyg4kwLDg/sADd9o7dGnReLpc0ojnZpsJwBe7AyqmYTv7Q7IfWBmo1Cic5G
FdUbFS77YcIdyU77e7S1iWIt642wJShodU6i6suqvbraR9rNv7YuDs37GRsECHlj
IDRP2GStQqVtyPWLZ8+yG+3COIq+eUD9atsqmGrAYCe4IVy1lDi37g7nupveIFTM
FqQP4NFhTKCEW0ZhnaTHukOOOKRsnec5KV1rbdtkFBH035ECrkIbUemPwuZv+hMH
WNq4cfE8osT6RsY0rxKdGrteUAb7LZJZ3EiK+f7agekO9rvtekq63tMPsbJz4JOj
vNeF0oifvrQYeL4Lv4OGxjI37pwCmbc/f95Dg9P6I9on9/h/Yyyejhlkd7nFNjDL
RhtikKR/at20QF2QKvAb+1CTexa9xIhzMY9ZxtCvQ/PJM5PRHxYv+kSDhfJqFoHc
be6SP2oXZEiXhVlWKCTnuUHjSa6sBgJlZDoT0k5mORWn64WQqBG+L+ywzvbqZX0J
08+mHvpDRQwzOOJg+3IQhsMQDaQ6w7nE9CEHv9Oh1mgoGDSPDr1NIYPRdZ5os1h5
w4sGjnxAzCTX36xU3XqkGLuDsOiBxkf+skIqZ88fr331KvQSbBw2Ia662q2SddDy
ArO3AgMBAAGjUzBRMB0GA1UdDgQWBBTopSzVEFFIz8Y6w270BvrEDDBPUDAfBgNV
HSMEGDAWgBTopSzVEFFIz8Y6w270BvrEDDBPUDAPBgNVHRMBAf8EBTADAQH/MA0G
CSqGSIb3DQEBCwUAA4ICAQCAD17WmP/yOv5I0QUXYgEYiJDVZvmDvOewWhKiTZDI
7hC6edDd4lx/hLmxzSOPHSj4K0wEA+0cVVArYCDp/uiWcV96c1531DdaYu/r2snd
FtUa8YhLB1jvBfxuTqJ1Q9+235PXDrOMprf4g7UMUk00M07D10ujIUorv0dccs3i
hmA+N83nHt9pGE2A2Cnwr++vmsy4jo9kqx5oXjAUovEP1xlOzP+tV6XjLy2tS4l1
rqfF48nnPzhK1nPUR/S7voHcvCfEV+LOCUp/PAZg0SbQDPTUBo0vajOtU4ChB84n
L5c/T2/NOHMR8kV+2d+b4rvoYaHaF9nFd0pC5d+vjAgn1BJRXXGP2tCSjxsMkwVO
C7KF8S1gXN+nXYCQbcrcRsAdCscSI+MJNv9IyMfxeZ/CtjBOQz4AYibrykp+EYL7
o0T9IW/1fjgBhC3qP/YXHLzkzUxdkktOsNdx7RzZNc0XACPcusnXx1Bw+YhQQFJT
sak7Fc8f0+4lFrQ6I2oVJ9CHWNDhSzxpXfY+JExOk8fytpvoFi4PyHyhWZOZOBSr
sshzq+cLKvLqR0rmUdrcC6PtXhM9got8xa/7cW5sbo393oZ720YEYhB4InpbmtDz
IawnZiugprouq6eaQ40KRv4xAJJXyX/yOHA0iGpjvqo8DLg5jzC8kIjulSUEIrgw
4w==
-----END CERTIFICATE-----
`)

func routerCaBundlePemBytes() ([]byte, error) {
	return _routerCaBundlePem, nil
}

func routerCaBundlePem() (*asset, error) {
	bytes, err := routerCaBundlePemBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/ca-bundle.pem", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerHttpbinDeployYaml = []byte(`apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: httpbin-pod
    labels:
      name: httpbin-pod
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: httpbin-pod
    template:
      metadata:
        labels:
          name: httpbin-pod
      spec:
        containers:
        - name: httpbin-http
          image: quay.io/openshifttest/httpbin@sha256:cc44fbd857f4148d8aad8359acc03efa719517e01d390b152e4f3830ad871c9f 
          ports:
          - containerPort: 8080
        - name: httpbin-https
          image: quay.io/openshifttest/httpbin@sha256:f57f4e682e05bcdadb103c93ae5ab9be166f79bcbbccaf45d92a2cad18da8d64
          ports:
          - containerPort: 8443
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: httpbin-svc-insecure
    name: httpbin-svc-insecure
  spec:
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 8080
    selector:
      name: httpbin-pod
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: httpbin-svc-secure
    name: httpbin-svc-secure
  spec:
    ports:
    - name: https
      port: 27443
      protocol: TCP
      targetPort: 8443
    selector:
      name: httpbin-pod
`)

func routerHttpbinDeployYamlBytes() ([]byte, error) {
	return _routerHttpbinDeployYaml, nil
}

func routerHttpbinDeployYaml() (*asset, error) {
	bytes, err := routerHttpbinDeployYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/httpbin-deploy.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerIngressWithClassYaml = []byte(`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-with-class
spec:
  ingressClassName: mytest
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          service:
            name: service-unsecure
            port:
              number: 27017
        path: /test
        pathType: ImplementationSpecific
`)

func routerIngressWithClassYamlBytes() ([]byte, error) {
	return _routerIngressWithClassYaml, nil
}

func routerIngressWithClassYaml() (*asset, error) {
	bytes, err := routerIngressWithClassYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/ingress-with-class.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerIngresscontrollerNpYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    domain: ${DOMAIN}
    replicas: 1
    endpointPublishingStrategy:
      type: NodePortService
    routeAdmission:
      namespaceOwnership: Strict
      wildcardPolicy: WildcardsDisallowed
parameters:
- name: NAME
- name: NAMESPACE
  value: openshift-ingress-operator
- name: DOMAIN
`)

func routerIngresscontrollerNpYamlBytes() ([]byte, error) {
	return _routerIngresscontrollerNpYaml, nil
}

func routerIngresscontrollerNpYaml() (*asset, error) {
	bytes, err := routerIngresscontrollerNpYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/ingresscontroller-np.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerSubdomainRoutesRouteYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
    labels:
      name: service-unsecure
    name: ${SUBDOMAIN_NAME}-unsecure
    namespace: ${NAMESPACE}
  spec:
    subdomain: ${SUBDOMAIN_NAME}
    to:
      kind: Service
      name: service-unsecure
parameters:
- name: NAMESPACE
- name: SUBDOMAIN_NAME
`)

func routerSubdomainRoutesRouteYamlBytes() ([]byte, error) {
	return _routerSubdomainRoutesRouteYaml, nil
}

func routerSubdomainRoutesRouteYaml() (*asset, error) {
	bytes, err := routerSubdomainRoutesRouteYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/subdomain-routes/route.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerTemplateWebServerDeployYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${DEPLOY_NAME}
      labels:
        name: ${DEPLOY_NAME}
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: ${DEPLOY_NAME}
      template:
        metadata:
          labels:
            name: ${DEPLOY_NAME}
        spec:
          containers:
          - image: quay.io/openshifttest/nginx-alpine@sha256:cee6930776b92dc1e93b73f9e5965925d49cff3d2e91e1d071c2f0ff72cbca29
            name: nginx
            ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: ${SVC_SECURE_NAME}
      name: ${SVC_SECURE_NAME}
    spec:
      ports:
      - name: https
        port: 27443
        protocol: TCP
        targetPort: 8443
      selector:
        name: ${DEPLOY_NAME}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: ${SVC_UNSECURE_NAME}
      name: ${SVC_UNSECURE_NAME}
    spec:
      ports:
      - name: http
        port: 27017
        protocol: TCP
        targetPort: 8080
      selector:
        name: ${DEPLOY_NAME}
parameters:
- name: DEPLOY_NAME
  value: web-server-deploy
- name: SVC_SECURE_NAME
  value: service-secure
- name: SVC_UNSECURE_NAME
  value: service-unsecure
`)

func routerTemplateWebServerDeployYamlBytes() ([]byte, error) {
	return _routerTemplateWebServerDeployYaml, nil
}

func routerTemplateWebServerDeployYaml() (*asset, error) {
	bytes, err := routerTemplateWebServerDeployYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/template-web-server-deploy.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerTestClientPodYaml = []byte(`apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-pod
  name: hello-pod
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: quay.io/openshifttest/nginx-alpine@sha256:cee6930776b92dc1e93b73f9e5965925d49cff3d2e91e1d071c2f0ff72cbca29
    name: hello-pod
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    ports:
    - containerPort: 8080
    - containerPort: 8443
`)

func routerTestClientPodYamlBytes() ([]byte, error) {
	return _routerTestClientPodYaml, nil
}

func routerTestClientPodYaml() (*asset, error) {
	bytes, err := routerTestClientPodYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/test-client-pod.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerWebServerDeployYaml = []byte(`apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: web-server-deploy
    labels:
      app: web-server-deploy
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: web-server-deploy
    template:
      metadata:
        labels:
          name: web-server-deploy
      spec:
        containers:
        - name: nginx
          image: quay.io/openshifttest/nginx-alpine@sha256:cee6930776b92dc1e93b73f9e5965925d49cff3d2e91e1d071c2f0ff72cbca29
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
- kind: Service
  apiVersion: v1
  metadata:
      labels:
          name: service-secure
      name: service-secure
  spec:
      ports:
         - name: https
           protocol: TCP
           port: 27443
           targetPort: 8443
      selector:
        name: web-server-deploy
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: service-unsecure
    name: service-unsecure
  spec:
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 8080
    selector:
      name: web-server-deploy`)

func routerWebServerDeployYamlBytes() ([]byte, error) {
	return _routerWebServerDeployYaml, nil
}

func routerWebServerDeployYaml() (*asset, error) {
	bytes, err := routerWebServerDeployYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/web-server-deploy.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerWebServerSignedDeployYaml = []byte(`apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nginx-config
  data:
    nginx.conf: |
      events {
          worker_connections 1024;
      }

      http {
          server {
              listen		8080;
              listen       [::]:8080;
              location / {
                  root /data/http;
              }
          }

          server {
              listen           	    8443 ssl http2 default;
              listen           	    [::]:8443 ssl http2 default;
              server_name      	    _;
              ssl_certificate  	    certs/tls.crt;
              ssl_certificate_key  	certs/tls.key;
              location / {
                  root /data/https-default;
              }
          }
      }
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: web-server-deploy
    labels:
      name: web-server-deploy
  spec:
    replicas: 1
    selector:
      matchExpressions:
       - {key: name, operator: In, values: [web-server-deploy]}
    template:
      metadata:
        labels:
          name: web-server-deploy
      spec:
        containers:
        - name: nginx
          image: quay.io/openshifttest/nginx-alpine@sha256:cee6930776b92dc1e93b73f9e5965925d49cff3d2e91e1d071c2f0ff72cbca29
          volumeMounts:
          - name: service-secret
            mountPath: /etc/nginx/certs/
          - name: nginx-config
            mountPath: /etc/nginx/
        volumes:
        - name: service-secret
          secret:
            secretName: service-secret
        - name: nginx-config
          configMap:
            name: nginx-config
- kind: Service
  apiVersion: v1
  metadata:
      annotations:
          service.beta.openshift.io/serving-cert-secret-name: service-secret
      labels:
          name: service-secure
      name: service-secure
  spec:
      ports:
         - name: https
           protocol: TCP
           port: 27443
           targetPort: 8443
      selector:
        name: web-server-deploy
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: service-unsecure
    name: service-unsecure
  spec:
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 8080
    selector:
      name: web-server-deploy
`)

func routerWebServerSignedDeployYamlBytes() ([]byte, error) {
	return _routerWebServerSignedDeployYaml, nil
}

func routerWebServerSignedDeployYaml() (*asset, error) {
	bytes, err := routerWebServerSignedDeployYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/web-server-signed-deploy.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerWebsocketDeployYaml = []byte(`apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: websocket
    labels:
      app: hello-websocket
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: hello-websocket
    template:
      metadata:
        labels:
          name: hello-websocket
      spec:
        containers:
        - name: hello-websocket
          image: quay.io/openshifttest/hello-websocket@sha256:d485f1fedd2bc929551e68288812c10957b99db3e833ec150071f00291ea77db
          ports:
          - containerPort: 9999
            name: http
            protocol: TCP
          - containerPort: 9443
            name: https
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: ws-unsecure
    name: ws-unsecure
  spec:
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 9999
    selector:
      name: hello-websocket
`)

func routerWebsocketDeployYamlBytes() ([]byte, error) {
	return _routerWebsocketDeployYaml, nil
}

func routerWebsocketDeployYaml() (*asset, error) {
	bytes, err := routerWebsocketDeployYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/websocket-deploy.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"router/49802-route.yaml":                router49802RouteYaml,
	"router/ca-bundle.pem":                   routerCaBundlePem,
	"router/httpbin-deploy.yaml":             routerHttpbinDeployYaml,
	"router/ingress-with-class.yaml":         routerIngressWithClassYaml,
	"router/ingresscontroller-np.yaml":       routerIngresscontrollerNpYaml,
	"router/subdomain-routes/route.yaml":     routerSubdomainRoutesRouteYaml,
	"router/template-web-server-deploy.yaml": routerTemplateWebServerDeployYaml,
	"router/test-client-pod.yaml":            routerTestClientPodYaml,
	"router/web-server-deploy.yaml":          routerWebServerDeployYaml,
	"router/web-server-signed-deploy.yaml":   routerWebServerSignedDeployYaml,
	"router/websocket-deploy.yaml":           routerWebsocketDeployYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"router": {nil, map[string]*bintree{
		"49802-route.yaml":          {router49802RouteYaml, map[string]*bintree{}},
		"ca-bundle.pem":             {routerCaBundlePem, map[string]*bintree{}},
		"httpbin-deploy.yaml":       {routerHttpbinDeployYaml, map[string]*bintree{}},
		"ingress-with-class.yaml":   {routerIngressWithClassYaml, map[string]*bintree{}},
		"ingresscontroller-np.yaml": {routerIngresscontrollerNpYaml, map[string]*bintree{}},
		"subdomain-routes": {nil, map[string]*bintree{
			"route.yaml": {routerSubdomainRoutesRouteYaml, map[string]*bintree{}},
		}},
		"template-web-server-deploy.yaml": {routerTemplateWebServerDeployYaml, map[string]*bintree{}},
		"test-client-pod.yaml":            {routerTestClientPodYaml, map[string]*bintree{}},
		"web-server-deploy.yaml":          {routerWebServerDeployYaml, map[string]*bintree{}},
		"web-server-signed-deploy.yaml":   {routerWebServerSignedDeployYaml, map[string]*bintree{}},
		"websocket-deploy.yaml":           {routerWebsocketDeployYaml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
