#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# tail the router pod output forever.

while :; do
    if router_pod=$(oc get pods -n openshift-ingress -l ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default -o=jsonpath='{.items[0].metadata.name}'); then
        if [ -n "$router_pod" ]; then
            if ! oc logs -f -n openshift-ingress "$router_pod"; then
                echo "Failed to fetch logs for pod $router_pod." >&2
            fi
        fi
    else
        echo "No router pod found or failed to get pods." >&2
    fi
    sleep 1
done
